site_name: 'Secure Suite Resource Guide'
pages:
  - "Welcome": index.md
  - "Benchmarks": benchmarks/BenchmarksGuide.md
  - "zzz": benchmarks/BenchmarksGuide.md
  - "CIS-CAT Pro Assessor": CIS-CAT/CIS-CATAssessorGuide.md
  - "CIS-CAT Pro Dashboard": CIS-CAT/CIS-CATDashboardGuide.md
  - "CIS Build Kits": remediation/RemediationGuide.md
theme:
  name: readthedocs
