site_name: CIS-CAT Pro Dashboard Document Library

nav:
    - Home: index.md
    - Source:      
        - Assessor v3 Deployment Guide: source/Assessor Deployment Guide.md
        - Change Log: source/Change Log.md
        - Dashboard Deployment Guide for Linux: source/Dashboard Deployment Guide for Linux.md
        - Dashboard Deployment Guide for Windows: source/Dashboard Deployment Guide for Windows.md
        - Dashboard User's Guide: source/Dashboard User's Guide.md

theme:
  name: readthedocs